version: 2

project_name: infoblox-exporter

before:
  hooks:
    - go mod tidy

builds:
  - id: infoblox-exporter
    main: .
    binary: infoblox-exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.version={{ .Version }} -X main.build={{ .ShortCommit }}

archives:
  - id: default
    ids:
      - infoblox-exporter
    formats:
      - tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: checksums.txt

source:
  enabled: true

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: elohmeier
    name: infoblox-exporter
